[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npx serve -s build -l $PORT"

[build.args]
NODE_VERSION = "18.17.0"

[build.environment]
NODE_ENV = "production"

[build.node]
version = "18.17.0"
