[phases.setup]
cmds = [
  "apt-get update && apt-get install -y curl",
  "curl -fsSL https://deb.nodesource.com/setup_18.x | bash -",
  "apt-get install -y nodejs"
]

[phases.install]
cmds = [
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm start"

[build.args]
NODE_VERSION = "18.17.0"

[build.environment]
NODE_ENV = "production"

[build.node]
version = "18.17.0"
